PPM_MULTIPLIER = 1_000_000.0
BBL_TO_GAL = 42.0

CONFIDENCE_HIGH = "HIGH"
CONFIDENCE_MEDIUM = "MEDIUM"
CONFIDENCE_LOW = "LOW"
CONFIDENCE_UNKNOWN = "UNKNOWN"

ACTUAL_METHOD_UNKNOWN = "UNKNOWN"
ACTUAL_METHOD_MEASURED = "MEASURED"
ACTUAL_METHOD_INFERRED_TANK = "INFERRED_TANK"
ACTUAL_METHOD_ALLOCATED = "ALLOCATED"
